version: '3'

services:
  zookeeper:
    container_name: zookeeper
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    networks:
      backend:
        aliases:
          - "zookeeper"
  kafkaserver:
    container_name: kafka
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS=dresses:1:1,ratings:1:1
    volumes:
        - "/var/run/docker.sock:/var/run/docker.sock"
    depends_on:
        - zookeeper
    networks:
        backend:
          aliases:
            - "kafka"
  redisserver:
    container_name: redis
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      backend:
        aliases:
          - "redis"
  database:
    container_name: database
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_prod"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    restart: always
    environment:
      KEYCLOAK_VERSION: 6.0.1
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ./config/realm-export.json:/opt/jboss/keycloak/realm-export.json
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/realm-export.json"
      - "-Dkeycloak.profile.feature.scripts=enabled"
      - "-Dkeycloak.profile.feature.upload_scripts=enabled"
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "keycloak"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata1:/usr/share/elasticsearch/data
    ports:
      # Maps the 9300 port as the cluster communication port
      - 9300:9300
      # Maps the 9200 port as the REST communication port
      - 9200:9200
    networks:
      backend:
        aliases:
          - "elasticsearch"
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9300"
    ports:
      - 5601:5601
    networks:
      backend:
        aliases:
          - "kibana"
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    container_name: logstash
    # Loads the Logstash config from a specific file or directory
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    # Mounts the configuration file in a Logstash running container
    volumes:
      - ./config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    networks:
      backend:
        aliases:
          - "logstash"
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    depends_on:
      - elasticsearch
    environment:
      - STORAGE_TYPE=elasticsearch
      - "ES_HOSTS=elasticsearch:9300"
    ports:
      - "9411:9411"
    networks:
      backend:
        aliases:
          - "zipkin"

  configserver:
    container_name: configserver
    image: ostock/configserver:0.0.1-SNAPSHOT
    ports:
      - "8071:8071"
      - "9071:9071"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      # add JAVA_TOOL_OPTIONS for remote debugging
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9071
    depends_on:
      - database
      - redisserver
      - kafkaserver
      - logstash
    networks:
      backend:
        aliases:
          - "configserver"

  eurekaserver:
    container_name: eurekaserver
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    ports:
      - "8070:8070"
      - "9070:9070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9070
    depends_on:
      - database
      - configserver
      - logstash
    networks:
      backend:
        aliases:
          - "eurekaserver"

  gatewayserver:
    container_name: gatewayserver
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    ports:
      - "8072:8072"
      - "9072:9072"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9072
    depends_on:
      - logstash
    networks:
      backend:
        aliases:
          - "gatewayserver"

  licensingservice:
    container_name: licensingservice
    #    Docker Compose first tries to find the target image to be started in the local Docker
    #    repository. If it can’t find it, it checks the central Docker Hub (http://hub.docker.com)
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    #    Defines the port numbers on the started Docker container, which are exposed to the outside world
    ports:
      - "8180:8180"
      - "9180:9180"
    environment:
      #      - Passes along environment variables to the starting Docker image. In this case, sets the
      #        SPRING_PROFILES_ACTIVE environment variable on the starting Docker image.
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9180
    depends_on:
      - database
      - configserver
      - logstash
    networks:
      backend:
        aliases:
          #          Specifies the alternative hostname for the service on the network
          - "licenseservice"

  organizationservice:
    container_name: organizationservice
    image: ostock/organization-service:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
      - "9081:9081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:9081
    depends_on:
      - database
      - configserver
      - logstash
    networks:
      - backend

networks:
  #  Creates a custom network named backend with the default type bridge
  backend:
    driver: bridge

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local
  esdata1:
    driver: local