#Spring framework implements a hierarchical mechanism for properties. First applied licensing-service.properties and
#after then licensing-service-dev.properties
example:
    gateway: http://localhost:8072
    property: I AM DEV
spring:
    # DataSource settings: set here your own configurations for the database
    datasource:
        password: '{cipher}1515c7968f9d30aa783d5a7eb416e17216a78ffdf6a63a54eb006f5baeee2dd7'
        url: jdbc:postgresql://localhost:5432/ostock_prod
        username: postgres
    flyway:
        baseline-version: 1
        password: '{cipher}1515c7968f9d30aa783d5a7eb416e17216a78ffdf6a63a54eb006f5baeee2dd7'
        url: jdbc:postgresql://localhost:5432/ostock_prod
        user: postgres
